### ISSUE TITLE
[External - Apizr.Integrations.Shiny] Register/Resolve IEnumerable<T>

### ISSUE THREAD

**Issue by JeremyBP** [Respawnsive/Apizr#1]
Waiting for external issues [#124](https://github.com/dansiegel/Prism.Container.Extensions/issues/124) and [#125](https://github.com/dansiegel/Prism.Container.Extensions/issues/125) to be fixed, so that Apizr could bring fusillade priority feature to DryIoc and Unity containers users and a smooth MediatR integration.
Also discussed [here](https://github.com/shinyorg/shiny/issues/369) on Shiny side.

**Comment by JeremyBP** [comment]
Dan just pushed its container extensions packages on NuGet with multiple instance registration/resolution feature, witch finally fix this. Please make sur to update to at least v8.0.48

**Comment by dorisoy** [comment]
> Dan刚刚使用多实例注册/解析功能将其容器扩展包推到了NuGet上，终于解决了这个问题。请使sur至少更新到v8.0.48

Hi, Jeremy BP, I recently tested your suggestion，the Prism.DryIoc.Extensions after upgrading to 8.0+, bug still exist.

crg.RegisterForNavigation<LazyContentPage<view1>, view1ViewModel>(nameof(view1)); 
crg.RegisterForNavigation<LazyContentPage<view2>, view2ViewModel>(nameof(view2));

"view2ViewModel" only work， "view1ViewModel" cannot be instantiated


> Dan just pushed its container extensions packages on NuGet with multiple instance registration/resolution feature, witch finally fix this. Please make sur to update to at least v8.0.48

**Comment by JeremyBP** [comment]
Do you guys could share a sample project?
I mean it doesn't look like to be related to Apizr. What you described is more about Prism and maybe you should consider to open an issue on its [repo](https://github.com/dansiegel/Prism.Container.Extensions).
Anyway, if you attach a sample project, I could investigate a bit.

**Comment by JeremyBP** [comment]
After some googling, I found that Prism doesn't allow multiple vm registration for same view AFAIK.
There's an old pull request about it but rejected: https://github.com/PrismLibrary/Prism/pull/1514
There's an entry on stackoverflow about it also: https://stackoverflow.com/a/52456663/14654700
The last vm registered will override others, in your case it's view2ViewModel.
