### ISSUE TITLE
Authentication Handler logs too much

### ISSUE THREAD

**Issue by powerdude** [Respawnsive/Apizr#7]
Hello,

I have an API that is called every few seconds and the log is full of these messages:

```
[Apizr - AuthenticationHandler`2: Authorization required with scheme Bearer] 
[Apizr - AuthenticationHandler`2: Saved token will be used] 
[Apizr - AuthenticationHandler`2: Authorization header has been set] 
[Apizr - AuthenticationHandler`2: Sending request with authorization header...] 
[Apizr - AuthenticationHandler`2: Token saved] 
```

Can the spots where the logger is called at least be guarded by `if (apizrVerbosity >= ApizrLogLevel.Low)`?

thanks

**Comment by JeremyBP** [comment]
Totally agree.
Will be available with v3 on witch I'm working on probably next week.

**Comment by JeremyBP** [comment]
This is now fixed and will be shipped with v3.

Also, if you're using Shiny integration, here is the hack I did to prevent Apizr log entries from being uploaded to AppCenter events:
```csharp
public void Write(string eventName, string description, params (string Key, string Value)[] parameters)
{
    if(!eventName.StartsWith(nameof(Apizr)) && !eventName.StartsWith(" ===")) // Hack to ignore events from Apizr (all is file logged)
        Analytics.TrackEvent($"[{eventName}] {description}", parameters.ToDictionary());
}
```

Please find more info about file logging here if interested: https://www.respawnsive.com/playground-part-3-catch-it-trace-it-log-it-and-upload-it/

**Comment by powerdude** [comment]
thank you for the feedback.  I look forward to the version which will have the fix.

**Comment by JeremyBP** [comment]
Hum... when I said next week, I forgot to tell of witch month :)
I'm pretty busy currently with some customer projects but I hope I could publish Apizr v3 soon.
It's close to be ready to go, just few things to fix/add.
Stay tuned!

**Comment by JeremyBP** [comment]
OMG thanks! 😅
